contest/contest/urls.py
from django.conf.urls import url
from django.contrib import admin

# For media
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),
]


# add to the bottom of your file
if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

contest/contestApp/urls.py
from django.conf.urls import url, include

# For Function views
#from . import views

# For Class bases views
from .views import IndexView, Pagina2View, Pagina3View, Pagina4View


urlpatterns = [
    # Function view
    # url(r'^$', views.index, name='index')
    # Class based biew
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^pagina2/$', Pagina2View.as_view(), name='pagina2'),
    url(r'^pagina3/$', Pagina3View.as_view(), name='pagina3'),
    url(r'^pagina4/$', Pagina4View.as_view(), name='pagina4'),
]

contest/contestApp/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime





"""Province model"""
class Province(models.Model):
    # Anadimos  campos al modelo
    name = models.CharField(
        max_length=255,
        verbose_name='Provincia'
    )

    # Como se mostrara en el admin cuando se le referencie
    def __unicode__(self):
        return self.name

    # Como se llama cuando hay varois en el admin
    class Meta:
        verbose_name = 'Provincia'
        verbose_name_plural = 'Provincias'


"""Participant model"""
class Participant(models.Model):

    name = models.CharField(
        max_length=40,
        verbose_name='Nombre'
    )

    surname = models.CharField(
        max_length=70,
        verbose_name='Apellidos'
    )

    dni = models.CharField(
        max_length=15,
        verbose_name='DNI/NIF'
    )

    email = models.EmailField(
        max_length=40,
        verbose_name='Email'
    )

    phone = models.CharField(
        max_length=40,
        verbose_name='Telafono'
    )

    profession = models.CharField(
        max_length=255,
        verbose_name='Profesion',
        null=True,
        blank=True
    )

    created = models.DateTimeField(
        verbose_name='Fecha del alta',
        auto_now_add=True,
        auto_now=False,
        blank=True
    )

    province = models.ForeignKey(
        Province,
        verbose_name='Provincia'
    )


    class Meta:
        verbose_name = 'Participante'
        verbose_name_plural = 'Participantes'

    def __unicode__(self):
        return self.name



"""Picture model"""
class Picture(models.Model):
    #objects = PictureManager()

    created = models.DateTimeField(
        verbose_name='Fecha creacion',
        default=datetime.now
    )

    url = models.ImageField(
        max_length=255,
        verbose_name='Imagen',
        upload_to='treasure_images',
        default='default.png',
        null=True,
        blank=True
    )

    description = models.CharField(
        max_length=255,
        verbose_name='Descripcion'
    )

    # Access to foreignkey values
    @property
    def get_votes(self):
        return Vote.objects.filter(foto=self.id).count()
    # define verbose name of a property for admin dashboard
    get_votes.fget.short_description = 'Num Votos'

    # Add thumbnail with popup to admin
    def image_img(self):
        if self.url:
            return u'<a onclick="return showAddAnotherPopup(this);" href="http://localhost:8000/media/%s" target="_blank"><img src="http://localhost:8000/media/%s" width="125px" height="auto"/></a>' % (self.url,self.url)
        elif self.url == '':
            return '(Sin imagen)'
        else:
            return '(Sin imagen)'
    image_img.short_description = 'Foto'
    # Allow insert html tags
    image_img.allow_tags = True

    class Meta:
        verbose_name = 'Imagen'
        verbose_name_plural = 'Imagenes'

    def __unicode__(self):
        return "Imagen %s" % self.id



class Vote(models.Model):
    foto = models.ForeignKey(
        Picture,
        verbose_name = 'Foto votada'
    )

    created = models.DateTimeField(
        verbose_name = 'Fecha voto',
        auto_now_add=True
    )

    email = models.EmailField(
        verbose_name = 'Email del votante'
    )

    def __unicode__(self):
        return "voto %s" % self.id

#objects = PictureManager()

#class PictureManager(models.Manager):
#    def get_votes(self):
#        queryset = Participant.objects.all()
#        return queryset.count()

contest/contestApp/forms.py
from django import forms
from .models import Picture, Vote
from django.contrib.admin import widgets

class PictureForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ['created', 'url', 'description']

class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = ['foto', 'email']

contest/contestApp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

# For generic view
from django.views.generic import TemplateView, FormView

from .models import Vote

# Form forms
from .forms import PictureForm, VoteForm
from django.http import HttpResponseRedirect

# Index Function view
#def index(request):
#    return render(request, 'index.html', {})



# Index class based view
class IndexView(TemplateView):
    template_name = 'index.html'

    # Context data
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        # Pasar por contexto
        #context['books'] = 'hola'
        #context['num'] = Vote.objects.filter(email='mivoto@gmail.com').count()
        return context

# Index class based view
class Pagina2View(FormView):
    template_name = 'pagina2.html'
    form_class = VoteForm
    success_url = "/pagina2/"

    # Context data
    def get_context_data(self, **kwargs):
        print('asd')
        context = super(Pagina2View, self).get_context_data(**kwargs)
        # Pasar por contexto
        context['books'] = 'hola'
        #context['num'] = Vote.objects.filter(email='mivoto@gmail.com').count()
        return context

    # Return if form is valid
    def form_valid(self, form,  **kwargs):
        print(self.request.POST['email'])
        vote = form.save(commit=False)
        # Get the data from email
        email = form.cleaned_data['email']
        print(email)
        # Validatiosn here
        vote.save()
        #return super(Pagina2View, self).form_valid(form)
        #return self.render_to_response(self.get_context_data(download_link=email))
        return self.render_to_response(self.get_context_data(download_link=email))

    # Return if form is invalid
    def form_invalid(self, form,  **kwargs):
        return self.render_to_response(self.get_context_data())






# Index class based view
class Pagina3View(FormView):
        template_name = 'pagina3.html'
        form_class = PictureForm
        success_url = "/pagina3/"

        # Context data
        def get_context_data(self, **kwargs):
            context = super(Pagina3View, self).get_context_data(**kwargs)
            # Pasar por contexto
            context['books'] = 'hola'
            #context['num'] = Vote.objects.filter(email='mivoto@gmail.com').count()
            return context

        # Return if form is valid
        def form_valid(self, form,  **kwargs):
            #print(self.request.POST['email'])
            picture = form.save(commit=False)
            # Get the data from email
            #email = form.cleaned_data['email']
            print(form.cleaned_data)
            # Validatiosn here
            picture.save()
            #return super(Pagina2View, self).form_valid(form)
            #return self.render_to_response(self.get_context_data(download_link=email))
            return self.render_to_response(self.get_context_data(download_link='Hecho'))

        # Return if form is invalid
        def form_invalid(self, form,  **kwargs):
            return self.render_to_response(self.get_context_data())


# Index class based view
class Pagina4View(TemplateView):
    template_name = 'pagina4.html'

contest/contestApp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <!-- core -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
  <!-- custom -->
  <link rel='stylesheet' href="{% static 'css/bootstrap.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link rel='stylesheet' media='screen and (max-width: 600px)' href="{% static 'css/bootstrap.min.css' %}" />
  <link rel='stylesheet' media='screen and (min-width: 601px) and (max-width: 992px)' href="{% static 'css/bootstrap.min.css' %}" />
  <link rel='stylesheet' media='screen and (min-width: 993px) and (max-width: 1307px)' href="{% static 'css/bootstrap.min.css' %}" />

  <title>Concurso</title>
</head>
<body>
<ul>
  <li><a href="{% url 'index' %}">pagina1</a></li>
  <li><a href="{% url 'pagina2' %}">pagina2</a></li>
  <li><a href="{% url 'pagina3' %}">pagina3</a></li>
  <li><a href="{% url 'pagina4' %}">pagina4</a></li>
</ul>

  {% block content %} 
  {% endblock %}
</body>
<script type="text/javascript" href="{% static 'js/jquery-3.0.0.min.js' %}">

</script>
</html>

contest/contestApp/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %} 
Contenido de index 
{% endblock %}

contest/contestApp/templates/pagina2.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %} 
contenido pagina 2
{{ books }}

{% if download_link %}
  -->{{ download_link }}<--
{% endif %}

{% if error %}
  -->{{ error }}<--
{% endif %}

<form action="" method="POST" class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>

<!-- errores en el formulario-->
{% if form.errors %}
    <ul>
    {% for error in form.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
  </ul>
{% endif %}

{% endblock %}

contest/contestApp/templates/pagina3.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %} 
contenido pagina 3


{% if download_link %}
  -->{{ download_link }}<--
{% endif %}

{% if error %}
  -->{{ error }}<--
{% endif %}

{% if not download_link %}
<!--
  <form action="" method="POST" class="post-form" enctype="multipart/form-data">
  {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
-->


<form action="" method="POST" class="post-form" enctype="multipart/form-data">
  {% csrf_token %}
    <p>
      <label for="id_created">Fecha creacion:</label>
      <input id="id_created" name="created" type="text" value="01/11/2016 22:11:34" />
      <input id="initial-id_created" name="initial-created" type="hidden" value="2016-11-01 22:11:34" />
    </p>
    <p>
      <label for="id_url">Imagen:</label>
      <input id="id_url" name="url" type="file" />
    </p>
    <p>
      <label for="id_description">Descripcion:</label>
      <input id="id_description" maxlength="255" name="description" type="text" />
    </p>
    <button type="submit" class="save btn btn-default">Save</button>
</form>

{% endif %}

{% endblock %}

contest/contestApp/templates/pagina4.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %} 
Contenido pagina4
{% endblock %}